
CREATE PROCEDURE CHANGE_MANAGER(P_DEPT_ID NUMBER,P_MANAGER_ID NUMBER) IS 

BEGIN 

UPDATE DEPARTMENTS
SET MANAGER_ID = P_MANAGER_ID
WHERE DEPARTMENT_ID = P_DEPT_ID;

END CHANGE_MANAGER;


CREATE FUNCTION
GET_MANAGER_DETAILS(P_DEPT_ID NUMBER)
RETURN
V_FNAME VARCHAR;
V_SNAME VARCHAR;

BEGIN
SELECT E.FIRST_NAME, E.LAST_NAME INTO V_FNAME, V_SNAME
FROM DEPARTMENTS D JOIN EMPLOYEES E 
ON(D.MANAGER_ID = E.MANAGER_ID)
WHERE D.DEPARTMENT_ID = P_DEPT_ID;

RETURN V_FNAME,V_SNAME;

END GET_MANAGER_DETAILS; 

SET SERVEROUTPUT ON;
EXECUTE DBMS_OUTPUT.PUT_LINE("MANAGER IS: " || GET_MANAGER_DETAILS(100));
